global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:8000"]

  - job_name: "prefect-orion"
    metrics_path: /api/admin/version
    static_configs:
      - targets: ["prefect-orion:4200"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
